from types import TracebackType

class Image:
    compression_quality: int
    def __init__(self, filename: str): ...
    def save(self, filename: str) -> None: ...
    def __enter__(self) -> Image: ...
    def __exit__(
        self, type: BaseException, value: BaseException, tb: TracebackType
    ) -> Image: ...
