from watchdog.events import FileSystemEventHandler

class Observer:
    def __init__(self) -> None: ...
    def is_alive(self) -> bool: ...
    def join(self) -> None: ...
    def schedule(self, handler: FileSystemEventHandler, path: str) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
